---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define nginx_user.
  set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

- name: Replace nginxg.conf
  template:
    src: templates/nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Add site.nginx.conf
  template:
    src: templates/artembf.pp.ua.conf
    dest: /etc/nginx/sites-available/

- name: Add site.security.conf
  template:
    src: templates/security.conf
    dest: /etc/nginx/nginxconfig.io/

- name: Add site.proxy.conf
  template:
    src: templates/proxy.conf
    dest: /etc/nginx/nginxconfig.io/

- name: Add site.general.conf
  template:
    src: templates/general.conf
    dest: /etc/nginx/nginxconfig.io/

- name: Create a symbolic link
  file:
    src: /etc/nginx/sites-available/artembf.pp.ua.conf
    dest: /etc/nginx/sites-enabled/artembf.pp.ua
    state: link
  notify:
    - nginx restart

