---
- name: Install nginx CentOS 7
  yum:
    name: nginx
    state: latest
  notify:
    - nginx systemd
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7"

- name: Install nginx Ubuntu 18
  apt:
    name: nginx
    state: latest
    update_cache: yes
  notify:
    - nginx systemd
  when: ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_major_version'] == "18"
