---
- import_tasks: install_remi.yml 
  when: ansible_facts['distribution'] == "CentOS"

- include_tasks: install.yml

- include_tasks: create_directory.yml

- include_tasks: copy_conf_file.yml

- include_tasks: firewall.yml
