---
- name: gluster start
  service:
    name: glusterd
    state: started
#    enabled: yes
#    name: glusterd

#- name: Make sure a service is enable
#  systemd:
#    enabled: yes
#    name: glusterd.service


