---
- name: Install remi repo.
  yum:
    name: "{{ remi_repo_url }}"
    state: present

- name: Import remi GPG key.
  rpm_key:
    key: "{{ remi_repo_gpg_key_url }}"
    state: present

- name: Enable REMI php-71 repo
  ini_file:
    dest: /etc/yum.repos.d/remi-php71.repo
    section: remi-php71
    option: enabled
    value: 1

#- name: Add remi-php71
#  yum_repository:
#    name: remi-php71
#    enabled: yes
#    state: update 

#- name: Add remi-php71
#  yum_repository:
#    name: remi-php71
#    description: Remi's PHP 7.1 RPM repository for Enterprise Linux $releasever - $basearch
#    mirrorlist: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
#    enabled: yes
#    gpgcheck: 1
#    gpgkey: http://rpms.remirepo.net/RPM-GPG-KEY-remi

#- name: Add multiple repositories into the same file (1/2)
#  yum_repository:
#    name: epel_r_l_7
#    description: EPEL YUM repo
#    file: external_repos
#    baseurl: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
#    enabled: yes

#- name: Add multiple repositories into the same file (2/2)
#  yum_repository:
#    name: remi_r_7
#    description: REMI YUM repo
#    file: external_repos
#    baseurl: http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
#    enabled: yes

#- name: Install EPEL Repo
#  yum:
#    name=epel-release
#    state=present
