---
# tasks file for /etc/ansible/roles/glusterd
- include_tasks: add_repo.yml

- include_tasks: install.yml

- import_tasks: gluster_conf.yml

#- name: Add line to hosts
#  lineinfile:
#    dest: /etc/hosts
#    line: maxretry = 3
#    create: yes


- import_tasks: ReadHat_firewalld.yml
  when: ansible_distribution == "CentOS"

- import_tasks: Debian_firewalld.yml
  when: ansible_distribution == "Ubuntu"

#- include_tasks: create_pool.yml

