---
- name: Gather the mariadb installed4
  package_facts:
    manager: auto

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: start_mariadb.yml
 
- include_tasks: secure-installation.yml 
  when: "'mariadb' not in ansible_facts.packages"

- include_tasks: create_user.yml

- include_tasks: firewalld.yml
