---
- name: install ntpd
  yum:
    name: ntp
    state: latest  

- name: enabled service ntpd
  systemd:
    name: ntpd
    enabled: yes

- name: start se4rvice ntpd
  systemd:
    name: ntpd
    state: started 
