---
- name: Include OS-specyfic variables
  include_vars: "{{ ansible_os_family  }}.yml"

- name: Define php_packages
  set_fact:
    php_packages: "{{ __php_packages | list }}"

- import_tasks: add_repo.yml

- import_tasks: install.yml
