---
- name: Create directory sites-available
  file:
    path: /etc/{{ apache2_conf_file_path }}/sites-available
    state: directory

- name: Create directory sites-enabled
  file:
    path: /etc/{{ apache2_conf_file_path }}/sites-enabled
    state: directory

- name: copy artembf.pp.ua conf
  template:
    src: templates/artembf.pp.ua.conf
    dest: /etc/{{ apache2_conf_file_path }}/sites-available/artembf.pp.ua.conf

#- name: copy artembf.pp.ua conf
#  template:
#    src: templates/artembf.pp.ua.conf
#    dest: /etc/"{{ apache2_conf_file_path }}"/sites-enabled/artembf.pp.ua.conf

- name: copy new httpd
  template:
    src: templates/{{ apache2_conf_name }}.conf
    dest: /etc/{{ apache2_conf_file_path_main }}/{{ apache2_conf_name }}.conf

- name: create link
  file:
    src: /etc/{{ apache2_conf_file_path }}/sites-available/artembf.pp.ua.conf
    dest: /etc/{{ apache2_conf_file_path }}/sites-enabled/artembf.pp.ua
    state: link
  notify:
    - httpd restarted
