---
- name: Add line to hosts
  lineinfile:
    dest: /etc/hosts
    line: 185.86.76.73 node1.com
    create: yes

- name: Add line to hosts
  lineinfile:
    dest: /etc/hosts
    line: 185.86.76.133 node2.com
    create: yes

- name: gluster peer probe 
  shell: gluster peer probe node2.com

- name: mkdir storage-pool
  file:
    path: /storage-pool
    state: directory

- name: Add line to hosts
  lineinfile:
    dest: /etc/fstab
    line: 'node1.com:/volume1   /storage-pool   glusterfs defaults,_netdev 0 0'
    create: yes

- name: create volume1
  shell: gluster peer probe node2.com

- name: Mount /storage-pool
  mount:
    path: /storage-pool
    src: node1.com:/volume1
    opts: bind
    state: mounted
    fstype: glusterfs 


#- name: Mount /storage-pool
#  mount:
#    path: /storage-pool
#    src: /boot
#    opts: bind
#    state: mounted
#    fstype: none
